version: '3'

services:
  nginx:
    container_name: nginui-nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: nginx:local
    command: /usr/sbin/nginx -g 'daemon off;'
    # command: /bin/bash
    cap_add:
      - NET_ADMIN
    ports:
      - "3013:3013"
  nginui-backend:
    build:
      context: .
    container_name: nginui-backend
    image: "nginui-backend:local"
    ports:
      - "3090:80"
  # nginui:
  #   build:
  #     context: .
  #   image: nginui:local
  #   command: /app/ovpn-admin
  #   environment:
  #     OVPN_DEBUG: "true"
  #     OVPN_VERBOSE: "true"
  #     OVPN_NETWORK: "192.168.100.0/24"
  #     OVPN_CCD: "true"
  #     OVPN_CCD_PATH: "/mnt/ccd"
  #     EASYRSA_PATH: "/mnt/easyrsa"
  #     OVPN_SERVER: "127.0.0.1:7777:tcp"
  #     OVPN_INDEX_PATH: "/mnt/easyrsa/pki/index.txt"
  #     OVPN_AUTH: "true"
  #     OVPN_AUTH_DB_PATH: "/mnt/easyrsa/pki/users.db"
  #     LOG_LEVEL: "debug"
  #   network_mode: service:openvpn
  #   volumes:
  #     - ./easyrsa_master:/mnt/easyrsa
  #     - ./ccd_master:/mnt/ccd

networks:
  default:
    name: nginui-network