version: '3'

services:
  nginui-backend:
    build:
      context: .
    container_name: nginui-backend
    image: "nginui-backend:local"
    ports:
      - "3090:80"
    volumes:
      - ./backend:/backend-dev
    command: 'bash /backend-entry-dev.sh'

  mongo:
    image: mongo
    restart: always
    container_name: nginui-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: nginui
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - nginui-mongo:/data/db

networks:
  default:
    name: nginui-network

volumes:
  nginui-mongo:
