version: '3'

services:
  nginui-backend:
    image: "nginui-backend:local"
    build:
      context: .
    container_name: nginui-backend
    environment:
      # MONGO_HOST: nginui-db
      # MONGO_USER: nginui
      # MONGO_PASSWORD: password
      # MONGO_DB: nginui
      CORS_ORIGINS: '["http://localhost:3000"]' # Note MUST be JSON format string
    ports:
      - "3090:80"
    volumes:
      - ./backend:/backend-dev
    command: 'bash /backend-entry-dev.sh'

  # mongo:
  #   image: mongo
  #   restart: always
  #   container_name: nginui-db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: nginui
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   volumes:
  #     - ./mongo:/data/db

networks:
  default:
    name: nginui-network

