version: '3'

services:
  nginui-backend-dev:
    build:
      context: .
    container_name: nginui-backend
    image: "nginui-backend:local"
    ports:
      - "3090:80"

  mongo:
    image: mongo
    restart: always
    container_name: nginui-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: nginui
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo:/data/db

networks:
  default:
    name: nginui-network